### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [lrs8810/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [ ] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
Hey Laura,

Overall, really solid work on this. Your top down design looks great. Your classes all make sense for the most part, the only issue is that some of the methods use attributes that you did not list. ie. `current_age: 2019 - 2002`, since there is no current age attribute. In addition, you have quite a few "Initial commit" messages in the repo, when a repo should only have one "Initial commit".

We'd like you to add 3rd class file and 3rd example object file. Make sure that you commit them separately using separate commit messages that provide appropriate context. In them, be sure that your methods use attributes that you have defined.

Great job in Mod-0 Laura. Reach out if you have any questions about this feedback or the instructions.

**Comment by lrs8810** [comment]
Hi David, 

Thank you so much for the feedback. Since the directory is already committed, I just need to add additional commit messages, correct? The directory only needs to be committed once, and my error was that I was committing each individual file.

**Comment by damwhit** [comment]
Any updates made to a directory will be timestamped and annotated via a commit. So for this project a commit messages might look like:

* Update class_2_example_object.txt
* Add class_2_example_object.txt
* Add class_2.txt

Note that these are providing context of what was done in the commit. The only exception to this rule is the "Initial commit", which should be the first commit message for a repo. The issue is that you have 6 "Initial commit" messages: https://github.com/lrs8810/mod_0_skills/commits/master

So we'd like you to:

* [x] Add a new file called class_3.txt, and commit it with a contextual commit message
  * be sure that your methods use only attributes that you have defined.
* [x] Add a new file called class_3_example_object.txt, and commit it with a contextual commit message
  * be sure that your methods use attributes that you have defined.
* [x] Any updates to the files should be made in commits with appropriate commit messages as well

**Comment by lrs8810** [comment]
Thank you so much for the explanation. I've completed the class_3.txt and class_3_example_object.txt files and pushed them to the remote repo.

**Comment by damwhit** [comment]
@lrs8810 nice work on your changes! You are officially `technical ready`

The only feedback I have is just a reminder on syntax. Arrays should be surrounded by brackets. so instead of: 

`("NASA", "Spongebob", "Sloth")` I would expect to see: `["NASA", "Spongebob", "Sloth"]`

**Comment by lrs8810** [comment]
@damwhit That's right. Thank you for the reminder!
